trigger:
  branches:
    include:
      - master
  batch: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: gulp@0
  displayName: 'gulp bundle'
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'bundle'
    arguments: '--ship'
    workingDirectory: '/'
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false    

- task: gulp@0
  displayName: 'gulp package-solution'
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'package-solution'
    arguments: '--ship'
    workingDirectory: '/'
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false

- task: CopyFiles@2
  inputs:
    SourceFolder: 'sharepoint/solution'
    Contents: '*'
    TargetFolder: '$(build.artifactstagingdirectory)/drop'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'ClientSideSolutions'
    publishLocation: 'Container'